[package]
name = "fver"
version = "0.1.0"
authors = ["ondralukes <mail@ondralukes.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simpletcp = "1.2.1"
openssl = "0.10.30"
dirs = "3.0.1"
hex = "0.4.2"